# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  enableCustomProcessTemplate: true
  customWorkItemType: 'Bug'
  customPTActiveStatus: 'In Progress'
  customPTNewStatus: 'New'
  customPTResolvedStatus: 'Resolved'
  customPTCloseStatus: 'Closed'

steps:

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '4e8bfa81642a57aa1171718613bf5695'
    apiKey: '6435ddc77711dc15a81660ebfd86ebbdbd99fa500a7d56ae10862cbdc21fc1a30cf4b5a77b41da77cab1d0b8636088ade9d9943bb95b74a491907064dc3927ae'
    veracodeAppProfile: 'InstaCheques'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    sandboxName: 'test'
    createSandBox: false
    createProfile: true
    failTheBuildIfVeracodeScanDidNotInitiate: false
    scanStatusCheckInterval: '60'
    importResults: false
    failBuildOnPolicyFail: false