# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: Veracode@2
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    username: 'saifullah.sk@moneymart.com'
    password: 'Mymoney@0021'
    veracodeAppProfile: 'InstaCheques'
#    version: '$(build.buildNumber)'
#    filepath: '$(build.artifactstagingdirectory)'
#    filepath: 'd:\a\1\s\WebGoat\bin'
    sandboxName: 'webgoat'
    createSandBox: false
    createProfile: false
    scanStatusCheckInterval: '60'
    importResults: true
    failBuildOnPolicyFail: true

- task: Veracode Flaw Importer@2
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    username: 'saifullah.dabir@outlook.com'
    password: 'Myoutlook@00'
    veracodeAppProfile: 'InstaCheques'
    sandboxName: 'webgoat'
    importType: 'All Unmitigated Flaws Violating Policy'
    workItemType: 'Bug'
    area: '$(system.teamProject)'
    flawImportLimit: '5000'